// src/components/Locales.tsx
import { locales } from '../i18n/locales'
import { useTranslation } from 'react-i18next'

export const Locales = () => {
    const { i18n } = useTranslation()

    const handleChangeLanguage = async (locale: string) => {
        i18n.changeLanguage(locale)
    }

    return (
        <div class="languages d-flex gap-x-2 ml-2">
            {locales.map(({ locale, ico }) => (
                <a key={locale} onClick={() => handleChangeLanguage(locale)}>
                    <img src={ico} width="30" height="23" class="rounded" />
                </a>
            ))}
        </div>
    )
}

// src/components/Locales.vue
<template>
  <div class="languages d-flex gap-x-2 ml-2">
    <a @click="() => setLocale('en')">
      <img src="/flags/usa.gif" width="30" height="23" class="rounded" />
    </a>
    <a @click="() => setLocale('ru')">
      <img src="/flags/russia.gif" width="30" height="23" class="rounded" />
    </a>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from "vue-i18n";

const { locale } = useI18n();

const setLocale = (value: string) => {
  locale.value = value;
};
</script>
