// src/App.tsx
import { Hero } from './components/Hero'
import { About } from './components/About'
import { Skills } from './components/Skills'

export const App = () => (
    <>
        <header>
            <Hero />
        </header>
        <main>
            <About />
            <Skills />
        </main>
    </>
)

// src/App.vue
<template>
  <header>
    <Hero />
  </header>
  <main>
    <About />
    <WorkExperience />
    <Skills />
  </main>
</template>

<script setup lang="ts">
import Hero from "./components/Hero.vue";
import About from "./components/About.vue";
import Skills from "./components/Skills.vue";
import WorkExperience from "./components/WorkExperience.vue";
</script>
